### PR TITLE
Package CachyOS-Settings for Fedora

### PR DESCRIPTION
**Pull request by 1Naim**
This brings more of CachyOS's changes to Fedora, e.g. modprobe and udev rules, pci-latency, and sysctl.d. It also includes kerver and bore-sysctl which were previously packaged separately so I took the liberty of deleting those spec files (can revert if needed)

This can also be considered as ground work for the uksmd replacement introduced since the release of systemd v256.
edit: this change isn't packaged yet since F40 is still on systemd v255

For now, the spec file, for better or for worse, matches upstream as it pulls in everything in the repo. This also means that leftover binaries that aren't used anymore but isn't deleted also gets packaged.

### CODE REVIEW

**Review by sirlucjan — APPROVED** [review]
LGTM @andersrh @TrixieUA

**Comment by andersrh** [comment]
I'm getting this error on Fedora Kinoite 40. 

Did you test it on Workstation? I assume this is the newest one I can test with? https://copr.fedorainfracloud.org/coprs/veilink/kernel-cachyos-test/package/cachyos-settings/

image

"Filen eksisterer" means that the file already exists.

**Comment by 1Naim** [comment]
I removed tunecfs and tunecfs2 in the recent commits because it was pulling ruby as a dependency. Those binaries are obviously not going to get used since we are on EEVDF now so I removed both. Currently I'm removing them via `rm` command. Let me know if there is a better way to do this since I am very new to this and very much want to learn.

**Comment by andersrh** [comment]
Screenshot_20240620_122907

Kinoite doesn't want to pull the latest version from the repo. I think it doesn't like that we are trying to obsolete some of the base system packages. That's just my guess. I have a hard time figuring out how we can replace zram-generator.conf.

**Comment by 1Naim** [comment]
> Screenshot_20240620_122907
> 
> Kinoite doesn't want to pull the latest version from the repo. I think it doesn't like that we are trying to obsolete some of the base system packages. That's just my guess. I have a hard time figuring out how we can replace zram-generator.conf.

are u installing the latest build? latest build is 1.0.0-6 but from your screenshot it still looks like ur installing 1.0.0-4

**Comment by andersrh** [comment]
> > Screenshot_20240620_122907
> > Kinoite doesn't want to pull the latest version from the repo. I think it doesn't like that we are trying to obsolete some of the base system packages. That's just my guess. I have a hard time figuring out how we can replace zram-generator.conf.
> 
> are u installing the latest build? latest build is 1.0.0-6 but from your screenshot it still looks like ur installing 1.0.0-4

yes. I have cleaned up cache so it should be aware of the latest version but i think it can't install the latest because of conflict so it goes back to an earlier version. does it work on Workstation?

**Comment by 1Naim** [comment]
yes it does work in workstation. can u try to install from the commandline instead? [This is the direct link to the working rpm file](https://download.copr.fedorainfracloud.org/results/veilink/kernel-cachyos-test/fedora-40-x86_64/07629238-cachyos-settings/cachyos-settings-1.0.0-6.fc40.x86_64.rpm).

**Comment by andersrh** [comment]
```
error: Could not depsolve transaction; 1 problem detected:
 Problem: package cachyos-settings-1.0.0-6.fc39.x86_64 from @commandline obsoletes zram-generator-defaults provided by zram-generator-defaults-1.1.2-11.fc39.noarch from @System
  - conflicting requests
```

This is the command I ran:
`rpm-ostree install https://download.copr.fedorainfracloud.org/results/veilink/kernel-cachyos-test/fedora-39-x86_64/07629238-cachyos-settings/cachyos-settings-1.0.0-6.fc39.x86_64.rpm`

Did it on my host system this time instead of VM so it's F39 instead of 40

**Comment by andersrh** [comment]
I'm testing this command: 

`rpm-ostree override remove zram-generator-defaults --install https://download.copr.fedorainfracloud.org/results/veilink/kernel-cachyos-test/fedora-39-x86_64/07629238-cachyos-settings/cachyos-settings-1.0.0-6.fc39.x86_64.rpm`

**Comment by 1Naim** [comment]
@andersrh The nature of this package probably just isn't compatible with immutable systems since it makes changes on the root directory that is read-only on Silverblue/Kinoite. FWIW I made a new [build](https://download.copr.fedorainfracloud.org/results/veilink/kernel-cachyos-test/fedora-40-x86_64/07629755-cachyos-settings/cachyos-settings-1.0.0-7.fc40.x86_64.rpm) that specifies the version of a package it obsoletes. If this one doesn't work then nothing else probably will. I'll get a few workstation users to test package install tho.

edit: your latest message just loaded for me :P let me know how that command goes. i wanted to suggest that command too since its the same command used to install the kernel.

**Comment by andersrh** [comment]
Screenshot_20240620_152003


Screenshot_20240620_152327

success

**Comment by andersrh** [comment]
bore-sysctl can be removed since BORE can't be customized since version 5. however I would like to keep kerver in a seperate package too, so we have the option to install it without all the customizations from cachyos-settings

**Comment by 1Naim** [comment]
Alright, i'll revert the commit one moment.

**Pull request merged**
